// Local task marketplace seed data.
// We kept the "Opportunity" type name so existing imports don't churn — read
// each field as a Task field (see comments). The core is: neighbors posting
// small paid work, and neighbors accepting it same-day for cash-fast pay.

export type Opportunity = {
  id: string;
  title: string;
  /** Poster's display name — e.g. "Sarah M." */
  company: string;
  category: string;
  categorySlug: string;
  /** Trust / speed badges — e.g. ["Same-day","ID verified","Cash-fast"] */
  tags: string[];
  payMin: number;
  payMax: number;
  payUnit: "hr" | "project" | "month" | "year" | "stipend";
  /** Duration — e.g. "~2 hrs" */
  hours: string;
  difficulty: "Entry" | "Intermediate" | "Advanced";
  experience: "Beginner" | "Any" | "Mid-level" | "Senior";
  /** True when the task can be done remotely (rare — most are local). */
  remote: boolean;
  /** Neighborhood + distance — e.g. "Riverside • 0.8 mi" */
  location: string;
  /** When needed — e.g. "Today • 3pm" */
  deadline: string;
  /** What helps (tools, skills). */
  skills: string[];
  summary: string;
  description: string;
  applyUrl: string;
  trending?: boolean;
  featured?: boolean;
  /** Hours ago the task was posted (mock; 0 = just now). */
  postedDaysAgo: number;
};

export const CATEGORIES = [
  "Moving",
  "Yard Work",
  "Dog Walking",
  "Cleaning",
  "Grocery Pickup",
  "Tech Help",
  "Tutoring",
  "Babysitting",
  "Painting",
  "Furniture Assembly",
  "Snow Removal",
  "Event Setup",
  "Photography",
  "Music Lessons",
  "Computer Repair",
  "House Sitting",
  "Elder Assistance",
  "Organization",
  "Car Washing",
  "Delivery",
  "Seasonal Work",
] as const;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const raw: Omit<Opportunity, "categorySlug">[] = [
  {
    id: "move-couch-riverside",
    title: "Help me move a couch up two flights",
    company: "Sarah M.",
    category: "Moving",
    tags: ["Same-day", "ID verified", "Two people"],
    payMin: 60, payMax: 60, payUnit: "project",
    hours: "~1 hr",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Riverside • 0.6 mi",
    deadline: "Today • 3:00 PM",
    skills: ["Lifting", "Bring a friend"],
    summary: "One couch, one apartment, two floors of stairs. Pay is cash on completion.",
    description: "Moving into a new walk-up and the couch won't fit in the elevator. Need one or two strong neighbors for about an hour. I've got water and I'll tip well if it goes smoothly.",
    applyUrl: "#",
    trending: true, featured: true, postedDaysAgo: 0,
  },
  {
    id: "yard-cleanup-north",
    title: "Fall leaf cleanup — front & back yard",
    company: "The Alvarez Family",
    category: "Yard Work",
    tags: ["Same-day", "Repeat gig", "Bring rake"],
    payMin: 25, payMax: 40, payUnit: "hr",
    hours: "3–4 hrs",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Northside • 1.2 mi",
    deadline: "This weekend",
    skills: ["Rake", "Leaf blower helpful"],
    summary: "Clear leaves, bag them, haul to curb. Could turn into weekly through winter.",
    description: "Small city lot, mostly maple leaves. If you're reliable, we'd love to book you weekly through the season. Cash or Venmo, your pick.",
    applyUrl: "#",
    featured: true, postedDaysAgo: 0,
  },
  {
    id: "dog-walk-daily",
    title: "Weekday lunchtime dog walk",
    company: "Marcus J.",
    category: "Dog Walking",
    tags: ["Recurring", "Same-day start", "Friendly dog"],
    payMin: 20, payMax: 25, payUnit: "hr",
    hours: "30 min / day",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Downtown • 0.4 mi",
    deadline: "Starts Monday",
    skills: ["Comfortable with dogs"],
    summary: "Golden retriever, easy walker, needs a 30-min midday walk M–F.",
    description: "Bailey is 4, friendly with everyone, no pulling. Key is in a lockbox. Pay is weekly, cash or transfer.",
    applyUrl: "#",
    trending: true, postedDaysAgo: 0,
  },
  {
    id: "deep-clean-2br",
    title: "Deep clean before family visits",
    company: "Priya S.",
    category: "Cleaning",
    tags: ["Same-day", "Supplies provided"],
    payMin: 120, payMax: 160, payUnit: "project",
    hours: "3–4 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Eastwood • 1.8 mi",
    deadline: "Tomorrow AM",
    skills: ["Attention to detail"],
    summary: "2BR apartment, top-to-bottom. My in-laws land Sunday. Please help.",
    description: "Kitchen, two bathrooms, floors, dusting. Supplies are here. Paid same day on completion.",
    applyUrl: "#",
    postedDaysAgo: 0,
  },
  {
    id: "grocery-run-elder",
    title: "Weekly grocery pickup for my mom",
    company: "Linda R.",
    category: "Grocery Pickup",
    tags: ["Recurring", "Trust-vetted", "Car required"],
    payMin: 25, payMax: 30, payUnit: "project",
    hours: "~45 min",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Maple Grove • 2.1 mi",
    deadline: "Every Thursday",
    skills: ["Car", "Careful with fragile items"],
    summary: "Pick up a small list at Wegmans, drop at my mom's front porch.",
    description: "Mom is 82 and doesn't drive anymore. Small weekly list, prepaid via my Wegmans account. Just need someone friendly and dependable.",
    applyUrl: "#",
    featured: true, postedDaysAgo: 0,
  },
  {
    id: "tech-help-wifi",
    title: "My WiFi is a mess — can someone fix it?",
    company: "Dr. Owens",
    category: "Tech Help",
    tags: ["Same-day", "Cash-fast"],
    payMin: 40, payMax: 60, payUnit: "hr",
    hours: "1–2 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Hilltop • 1.5 mi",
    deadline: "Today, anytime",
    skills: ["Networking basics", "Router setup"],
    summary: "New router won't cooperate. Need it working by tonight.",
    description: "I have the router, the ISP account details, and one very frustrated home office. Whoever gets this working today gets paid today.",
    applyUrl: "#",
    trending: true, postedDaysAgo: 0,
  },
  {
    id: "tutor-8th-math",
    title: "8th-grade algebra tutor — 2x / week",
    company: "The Kim Family",
    category: "Tutoring",
    tags: ["Recurring", "Evenings"],
    payMin: 30, payMax: 45, payUnit: "hr",
    hours: "1 hr sessions",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Willow Park • 0.9 mi",
    deadline: "Starts this week",
    skills: ["Algebra", "Patience"],
    summary: "Kind, patient tutor for our daughter — Tue/Thu evenings.",
    description: "She's smart but stuck on quadratics. Someone warm who explains things a few different ways would be perfect. Paid weekly.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "babysit-friday-night",
    title: "Friday-night babysitter for two kids",
    company: "Ana & Jamal",
    category: "Babysitting",
    tags: ["One-time", "Background-check preferred"],
    payMin: 25, payMax: 30, payUnit: "hr",
    hours: "5 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Southbank • 1.1 mi",
    deadline: "This Friday, 6–11 PM",
    skills: ["CPR a plus", "Great with kids"],
    summary: "Two kids (5 and 7), pizza dinner, movie, in bed by 9.",
    description: "First-time using the app so we'd love someone with a rating already. Easy night — they know the routine.",
    applyUrl: "#",
    postedDaysAgo: 0,
  },
  {
    id: "paint-bedroom",
    title: "Paint one small bedroom",
    company: "Trent H.",
    category: "Painting",
    tags: ["Same-day", "Materials provided"],
    payMin: 200, payMax: 275, payUnit: "project",
    hours: "6–8 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Old Town • 2.4 mi",
    deadline: "Sat or Sun",
    skills: ["Cutting-in", "Clean work"],
    summary: "10×12 bedroom, one accent wall. Paint and supplies are here.",
    description: "Moving day is Monday and this room needs to look sharp. Careful lines around trim more important than speed.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "ikea-assembly-3",
    title: "Assemble 3 IKEA pieces (dresser + 2 shelves)",
    company: "Camila V.",
    category: "Furniture Assembly",
    tags: ["Same-day", "Tools helpful"],
    payMin: 90, payMax: 120, payUnit: "project",
    hours: "~2 hrs",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Riverside • 0.7 mi",
    deadline: "Today or tomorrow",
    skills: ["Basic tools", "Patience with instructions"],
    summary: "Boxes are on my living room floor. Please make them furniture.",
    description: "MALM dresser and two KALLAX shelves. Instructions in the box. I'll be here with coffee.",
    applyUrl: "#",
    trending: true, postedDaysAgo: 0,
  },
  {
    id: "snow-driveway-season",
    title: "Driveway shoveling — all winter",
    company: "Mr. Petrov",
    category: "Snow Removal",
    tags: ["Seasonal", "Recurring", "Reliable pay"],
    payMin: 30, payMax: 50, payUnit: "project",
    hours: "45 min / storm",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Northside • 1.3 mi",
    deadline: "This season",
    skills: ["Own shovel", "Snow-blower a plus"],
    summary: "Every storm 3+ inches. Cleared before 8am. Cash per storm.",
    description: "Small driveway plus a short walk. I'm 71 and my back is done with it. Pay after each storm, no waiting.",
    applyUrl: "#",
    featured: true, postedDaysAgo: 2,
  },
  {
    id: "event-setup-birthday",
    title: "Help set up my kid's 6th birthday party",
    company: "Nadia F.",
    category: "Event Setup",
    tags: ["One-time", "Weekend"],
    payMin: 25, payMax: 35, payUnit: "hr",
    hours: "3 hrs",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Southbank • 1.6 mi",
    deadline: "Sat 10 AM",
    skills: ["Balloons", "Cheerful energy"],
    summary: "Tables, streamers, balloon arch, backyard setup.",
    description: "Party is 12–3. Need setup done by 11:30. Someone patient with a glue gun preferred.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "photo-family-shoot",
    title: "Family photos in the park",
    company: "The Bello family",
    category: "Photography",
    tags: ["One-time", "Weekend"],
    payMin: 175, payMax: 250, payUnit: "project",
    hours: "60–90 min",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Willow Park • 0.8 mi",
    deadline: "Sunday afternoon",
    skills: ["Own camera", "Basic editing"],
    summary: "Golden hour shoot, five people including grandma. ~20 edited photos.",
    description: "Casual — not too posed. We love laughs and candids. Delivery via Google Drive within a week.",
    applyUrl: "#",
    postedDaysAgo: 2,
  },
  {
    id: "guitar-lessons-kid",
    title: "Beginner guitar lessons for my 10-year-old",
    company: "Devon S.",
    category: "Music Lessons",
    tags: ["Recurring", "Weekends"],
    payMin: 30, payMax: 45, payUnit: "hr",
    hours: "45 min / week",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Eastwood • 1.7 mi",
    deadline: "Starting next Sat",
    skills: ["Great with kids", "Patient teaching"],
    summary: "First lessons — kindness matters more than speed.",
    description: "He has a 3/4 acoustic. We're not building a virtuoso, just growing a love for it. Paid weekly.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "computer-slow-repair",
    title: "My laptop is crawling — can someone tune it up?",
    company: "Eileen T.",
    category: "Computer Repair",
    tags: ["Same-day", "Cash-fast"],
    payMin: 50, payMax: 80, payUnit: "project",
    hours: "1–2 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Downtown • 0.5 mi",
    deadline: "Today",
    skills: ["Windows cleanup", "Backups"],
    summary: "5-year-old Windows laptop. Takes 4 minutes to open a browser.",
    description: "Photos of my grandkids are on it — please back them up before anything else. I can pay cash today.",
    applyUrl: "#",
    trending: true, postedDaysAgo: 0,
  },
  {
    id: "housesit-week",
    title: "House-sit + water plants (one week)",
    company: "Nora K.",
    category: "House Sitting",
    tags: ["One-time", "Trust-vetted"],
    payMin: 300, payMax: 400, payUnit: "project",
    hours: "1 week",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Hilltop • 2.0 mi",
    deadline: "Aug 10–17",
    skills: ["Reliable", "Reference from a neighbor"],
    summary: "Sleep here, water plants, bring in mail. Quiet street.",
    description: "Traveling for work. Cat is with a friend. Just need a warm body and someone who won't throw a party.",
    applyUrl: "#",
    postedDaysAgo: 2,
  },
  {
    id: "elder-companion-walk",
    title: "Afternoon walks with my dad",
    company: "Rick J.",
    category: "Elder Assistance",
    tags: ["Recurring", "Meaningful"],
    payMin: 22, payMax: 28, payUnit: "hr",
    hours: "1 hr, 3x / week",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Maple Grove • 2.3 mi",
    deadline: "Starting soon",
    skills: ["Patient", "Warm conversation"],
    summary: "Dad is 78, sharp as ever, needs a walking buddy.",
    description: "Loop around the neighborhood or the park. He'll tell you stories. You'll leave smiling.",
    applyUrl: "#",
    featured: true, postedDaysAgo: 1,
  },
  {
    id: "closet-organize",
    title: "Organize my hall closet — top to bottom",
    company: "Beth W.",
    category: "Organization",
    tags: ["One-time", "Same-day"],
    payMin: 30, payMax: 45, payUnit: "hr",
    hours: "3 hrs",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Old Town • 1.9 mi",
    deadline: "This week",
    skills: ["Sorting", "Labeling"],
    summary: "Chaos. Bins welcome. I need a fresh eye.",
    description: "Everything from linens to holiday stuff. Bring an opinion and a label maker if you have one.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "car-wash-detail",
    title: "Wash + interior detail on our SUV",
    company: "Omar A.",
    category: "Car Washing",
    tags: ["Same-day", "Cash-fast"],
    payMin: 60, payMax: 90, payUnit: "project",
    hours: "~2 hrs",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Southbank • 1.4 mi",
    deadline: "Sat morning",
    skills: ["Vacuum", "Interior wipe-down"],
    summary: "Wash the outside, vacuum the crumbs, wipe the interior.",
    description: "Two kids and a dog have done real damage. I have hose access and supplies.",
    applyUrl: "#",
    postedDaysAgo: 0,
  },
  {
    id: "grocery-delivery-costco",
    title: "Costco run + delivery to my door",
    company: "Jules P.",
    category: "Delivery",
    tags: ["Same-day", "Car required"],
    payMin: 40, payMax: 55, payUnit: "project",
    hours: "~90 min",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Northside • 1.0 mi",
    deadline: "Today or tomorrow",
    skills: ["SUV / hatchback", "Careful driver"],
    summary: "Short list, mostly heavy stuff. Pay + reimburse in cash.",
    description: "I'll send the list and my membership. Bring receipts, I pay back plus your fee same day.",
    applyUrl: "#",
    postedDaysAgo: 0,
  },
  {
    id: "seasonal-firewood",
    title: "Stack a cord of firewood",
    company: "The Hallens",
    category: "Seasonal Work",
    tags: ["One-time", "Physical"],
    payMin: 120, payMax: 160, payUnit: "project",
    hours: "3–4 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Hilltop • 2.2 mi",
    deadline: "This weekend",
    skills: ["Strong back", "Gloves"],
    summary: "Delivery drops on the driveway. We need it stacked along the fence.",
    description: "Real work. Water and snacks provided. Pay bumps if you get it done in under 3.",
    applyUrl: "#",
    postedDaysAgo: 2,
  },
  {
    id: "tech-help-smart-tv",
    title: "Set up my new smart TV + soundbar",
    company: "Gene L.",
    category: "Tech Help",
    tags: ["Same-day", "Under an hour"],
    payMin: 50, payMax: 70, payUnit: "project",
    hours: "45–60 min",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Downtown • 0.3 mi",
    deadline: "Today evening",
    skills: ["HDMI wrangling", "Streaming apps"],
    summary: "Mount is up. TV is in the box. Please make football happen by Sunday.",
    description: "You'll be my hero. Cash on completion.",
    applyUrl: "#",
    postedDaysAgo: 0,
  },
  {
    id: "yard-mow-recurring",
    title: "Biweekly lawn mow — small yard",
    company: "The Diazes",
    category: "Yard Work",
    tags: ["Recurring", "Bring mower"],
    payMin: 40, payMax: 55, payUnit: "project",
    hours: "45 min",
    difficulty: "Entry", experience: "Any", remote: false,
    location: "Willow Park • 1.0 mi",
    deadline: "Every other Sat",
    skills: ["Own mower", "Edging"],
    summary: "Small front + back. Reliable, friendly, and paid every visit.",
    description: "Trying to lock in someone for the season. Cash or Venmo after each mow.",
    applyUrl: "#",
    postedDaysAgo: 1,
  },
  {
    id: "cleaning-move-out",
    title: "Move-out clean — one bedroom apartment",
    company: "Alicia B.",
    category: "Cleaning",
    tags: ["One-time", "Deposit-back"],
    payMin: 150, payMax: 220, payUnit: "project",
    hours: "4 hrs",
    difficulty: "Intermediate", experience: "Any", remote: false,
    location: "Eastwood • 2.0 mi",
    deadline: "Aug 30",
    skills: ["Oven + fridge", "Bathroom deep clean"],
    summary: "Empty apartment, needs to sparkle for the walk-through.",
    description: "Landlord is picky. If you're thorough I'll tip on top for a clean walk-through.",
    applyUrl: "#",
    postedDaysAgo: 3,
  },
];

export const OPPORTUNITIES: Opportunity[] = raw.map((o) => ({
  ...o,
  categorySlug: slug(o.category),
}));

export function getOpportunity(id: string) {
  return OPPORTUNITIES.find((o) => o.id === id);
}

export function formatPay(o: Opportunity) {
  const unit = { hr: "/hr", project: " flat", month: "/mo", year: "/yr", stipend: " total" }[o.payUnit];
  const fmt = (n: number) => (n >= 1000 ? `$${(n / 1000).toFixed(n % 1000 === 0 ? 0 : 1)}k` : `$${n}`);
  return o.payMin === o.payMax ? `${fmt(o.payMin)}${unit}` : `${fmt(o.payMin)}–${fmt(o.payMax)}${unit}`;
}

export function postedLabel(hoursAgo: number) {
  if (hoursAgo <= 0) return "Just posted";
  if (hoursAgo === 1) return "1 hr ago";
  if (hoursAgo < 24) return `${hoursAgo} hrs ago`;
  const d = Math.round(hoursAgo / 24);
  return d === 1 ? "1 day ago" : `${d} days ago`;
}
