/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostRouteImport } from './routes/post'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AvailableRouteImport } from './routes/available'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailableRoute = AvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssessmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/available': typeof AvailableRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/available': typeof AvailableRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/available': typeof AvailableRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/post': typeof PostRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/assessments'
    | '/available'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/opportunities'
    | '/post'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/terms'
    | '/assessments/$id'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/assessments'
    | '/available'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/opportunities'
    | '/post'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/terms'
    | '/assessments/$id'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/assessments'
    | '/available'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/opportunities'
    | '/post'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/terms'
    | '/assessments/$id'
    | '/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  AvailableRoute: typeof AvailableRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PostRoute: typeof PostRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/available': {
      id: '/available'
      path: '/available'
      fullPath: '/available'
      preLoaderRoute: typeof AvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsIdRoute: typeof AssessmentsIdRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsIdRoute: AssessmentsIdRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  AvailableRoute: AvailableRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PostRoute: PostRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
